version: 1

trail:
  attestations:
    - name: tf-plan-beta
      type: generic
    - name: tf-plan-prod
      type: generic
  artifacts:
    - name: state-beta
    - name: state-prod
    - name: differ
      attestations:
        - name: lint
          type: generic
        - name: pull-request
          type: pull_request
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
        - name: unit-test
          type: junit
        - name: branch-coverage
          type: generic
