version: 1

trail:
  attestations:
    - name: lint
      type: generic
    - name: pull-request
      type: pull_request

  artifacts:
    - name: differ
      attestations:
        - name: snyk-scan
          type: snyk
        - name: unit-test
          type: junit
        - name: branch-coverage
          type: generic
