version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request
#    - name: never-alone-data
#      type: generic
#    - name: never-alone-control
#      type: generic
  artifacts:
    - name: differ
      attestations:
        - name: lint
          type: generic
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
        - name: unit-test
          type: junit
        - name: branch-coverage
          type: generic
#        - name: sonarcloud-scan
#          type: sonar
