AllCops:
    NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - app/server/app_base.rb

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'
    - app/client/html_demo.rb
    - app/server/git_diff_parser.rb
    - app/server/external/sheller.rb
    - app/server/differ.rb
    - app/client/http_json_hash/service_error.rb

Style/Documentation:
  Exclude:
    - '*/**/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - test/*/lib/id58_test_base.rb
    - app/server/git_diff_parser.rb

Metrics/AbcSize:
  Exclude:
    - test/*/lib/simplecov_json.rb
    - test/*/lib/id58_test_base.rb
    - app/server/git_diff_parser.rb


Metrics/ClassLength:
  Exclude:
    - test/client/differ_client_test.rb
    - test/server/git_diff_parse_filenames_test.rb
    - test/server/git_diff_parser_test.rb
    - test/server/differ_test.rb
    - test/server/diff_summary_test.rb
    - app/server/git_diff_parser.rb

Style/FormatStringToken:
  Exclude:
    - test/*/lib/id58_test_base.rb

Layout/LineLength:
  Exclude:
    - test/*/lib/simplecov_json.rb

Style/ClassVars:
  Exclude:
    - test/*/lib/id58_test_base.rb

Naming/VariableNumber:
  Exclude:
    - app/server/external/gitter.rb

Metrics/ParameterLists:
  Exclude:
    - test/server/saver.rb
    - app/client/saver.rb

Style/OpenStructUse:
  Exclude:
    - test/server/prober_test.rb
    - test/server/http_adapter_stub.rb
    - test/client/http_response_unpacker_test.rb

Lint/RescueException:
  Exclude:
    - app/client/client.rb

Lint/SymbolConversion:
  Exclude:
    - app/server/app_base.rb
    - test/*/lib/id58_test_base.rb

Style/FetchEnvVar:
  Exclude:
    - app/server/app_base.rb

Style/HashConversion:
  Exclude:
    - app/server/app_base.rb

Style/HashTransformKeys:
  Exclude:
    - app/server/app_base.rb



