AllCops:
  NewCops: enable
  Exclude:
    - test/**/*

Lint/RescueException:
  Exclude:
    - source/client/client.rb

Lint/SymbolConversion:
  Exclude:
    - source/server/app_base.rb

Metrics/AbcSize:
  Exclude:
    - source/server/git_diff_parser.rb

Metrics/BlockLength:
  Exclude:
    - source/server/app_base.rb

Metrics/ClassLength:
  Exclude:
    - source/server/git_diff_parser.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - source/server/git_diff_parser.rb

Metrics/MethodLength:
  Exclude:
    - source/client/html_demo.rb
    - source/server/git_diff_parser.rb
    - source/server/external/sheller.rb
    - source/server/differ.rb
    - source/client/http_json_hash/service_error.rb

Metrics/ParameterLists:
  Exclude:
    - source/client/saver.rb

Naming/VariableNumber:
  Exclude:
    - source/server/external/gitter.rb

Style/Documentation:
  Exclude:
    - '*/**/*.rb'

Style/FetchEnvVar:
  Exclude:
    - source/server/app_base.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - source/**/*

Style/HashConversion:
  Exclude:
    - source/server/app_base.rb

Style/HashTransformKeys:
  Exclude:
    - source/server/app_base.rb
