
fullnameOverride: "differ"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: differ-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: differ
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: differ-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        memory: 64Mi
    livenessProbe:
      path: /alive
    readinessProbe:
      path: /ready
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_CUSTOM_START_POINTS_PORT: "4526"
      CYBER_DOJO_EXERCISES_START_POINTS_PORT: "4525"
      CYBER_DOJO_LANGUAGES_START_POINTS_PORT: "4524"
      CYBER_DOJO_CREATOR_PORT: "4523"
      CYBER_DOJO_DASHBOARD_PORT: "4527"
      CYBER_DOJO_DIFFER_PORT: "4567"
      CYBER_DOJO_MODEL_PORT: "4528"
      CYBER_DOJO_NGINX_PORT: "80"
      CYBER_DOJO_REPLER_PORT: "4657"
      CYBER_DOJO_RUNNER_PORT: "4597"
      CYBER_DOJO_SAVER_PORT: "4537"
      CYBER_DOJO_SHAS_PORT: "4522"
      CYBER_DOJO_WEB_PORT: "3000"
