name: Build image

on:
  push:
    branches:
      - main

jobs:

  with-vars:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.with_vars.outputs.image_tag }}
      aws_account_id_beta: ${{ steps.with_vars.outputs.aws_account_id_beta }}
      aws_account_id_prod: ${{ steps.with_vars.outputs.aws_account_id_prod }}
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      id: with_vars
      run: |
        echo "image_tag=$(echo $GITHUB_SHA | head -c7)" >> ${GITHUB_OUTPUT}
        echo "aws_account_id_beta=244531986313"         >> ${GITHUB_OUTPUT} 
        echo "aws_account_id_prod=274425519734"         >> ${GITHUB_OUTPUT} 

  build:
    needs: [with-vars]
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run:
          ./sh/build.sh

      - name: Push image to public registry (dockerhub)
        run: |
          echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
          docker push cyberdojo/differ:${{ needs.with-vars.outputs.image_tag }}
          docker logout

  kosli-production:
    needs: [with-vars, build]
    uses: cyber-dojo/differ/.github/workflows/test_and_deploy.yml@main
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      KOSLI_HOST: https://app.kosli.com  #<<<<<<<<
      IMAGE_TAG: ${{ needs.with-vars.outputs.image_tag }}
      AWS_ACCOUNT_ID_BETA: ${{ needs.with-vars.outputs.aws_account_id_beta }}
      AWS_ACCOUNT_ID_PROD: ${{ needs.with-vars.outputs.aws_account_id_prod }}

  kosli-staging:
    needs: [with-vars, kosli-production]
    uses: cyber-dojo/differ/.github/workflows/test_and_deploy.yml@main
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      KOSLI_HOST: https://staging.app.kosli.com  #<<<<<<<<
      IMAGE_TAG: ${{ needs.with-vars.outputs.image_tag }}
      AWS_ACCOUNT_ID_BETA: ${{ needs.with-vars.outputs.aws_account_id_beta }}
      AWS_ACCOUNT_ID_PROD: ${{ needs.with-vars.outputs.aws_account_id_prod }}

