name: Deploy-manually to aws-beta

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (short commit SHA - first 7 digits)'
        required: true

jobs:
  deploy_to_beta:
    uses: ./.github/workflows/sub_deploy_to_beta.yml
    with:
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}

  attest_beta_artifacts:
    needs: [deploy_to_beta]
    uses: ./.github/workflows/attest_tf_beta_artifacts.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
