name: Sub - expect-deployment

on:
  workflow_call:
    secrets:
      KOSLI_API_TOKEN:
        required: true
    inputs:
      KOSLI_HOST:
        default: https://app.kosli.com
        required: false
        type: string
      IMAGE_TAG:
        required: true
        type: string

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST: ${{ inputs.KOSLI_HOST }}
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }}
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

jobs:

  to-aws-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Report expected aws-beta deployment to Kosli
        run: |
          docker pull cyberdojo/differ:${{ inputs.IMAGE_TAG }}          
          kosli expect deployment cyberdojo/differ:${{ inputs.IMAGE_TAG }} \
            --artifact-type=docker \
            --description="Deployed to aws-beta in Github Actions pipeline" \
            --environment=aws-beta

  to-aws-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Report expected aws-prod deployment to Kosli
        run: |
          docker pull cyberdojo/differ:${{ inputs.IMAGE_TAG }}          
          kosli expect deployment cyberdojo/differ:${{ inputs.IMAGE_TAG }} \
            --artifact-type=docker \
            --description="Deployed to aws-prod in Github Actions pipeline" \
            --environment=aws-prod
