name: Sub - push :latest image to dockerhub

on:
  workflow_call:
    secrets:
      DOCKER_PASS:
        required: true
      DOCKER_USER:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

jobs:
  to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image:latest to Dockerhub Registry
        run: |
          docker pull cyberdojo/differ:${{ inputs.IMAGE_TAG }}  
          docker tag cyberdojo/differ:${{ inputs.IMAGE_TAG }} cyberdojo/differ:latest
          docker push cyberdojo/differ:latest
