name: environment-reporter terraform apply

on:
  push:
    paths:
      - 'deployment/terraform/environment-reporter/**'


jobs:
  deploy:
    permissions:
      id-token: write
      contents: write
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.23
    strategy:
      fail-fast: false
      matrix:
        environment: [beta, prod]
        include:
          - AWS_ACCOUNT_ID: 244531986313
            environment: beta
          - AWS_ACCOUNT_ID: 274425519734
            environment: prod
    with:
      aws_region: eu-central-1
      aws_default_region: eu-central-1
      aws_role_arn: arn:aws:iam::${{ matrix.aws_account_id }}:role/gh_actions_services
      aws_role_duration: 900
      working_directory: deployment/terraform/environment-reporter
      tf_apply: 'true'
      tf_version: v1.9.1
      tf_additional_env_vars: '{"TF_VAR_KOSLI_HOST": "${{ vars.KOSLI_HOST }}"}'